In [55]:
#import liabry and load in the files

import pandas as pd
import os

Systembook = pd.read_csv("03_Library Systembook.csv")

Customer = pd.read_csv("03_Library SystemCustomers.csv")

display(Systembook.head())
display(Customer.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [56]:
Systembook[Systembook["Books"].isna()]

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
20,21.0,NaN,"""01/06/2023""",05/06/2023,2 weeks,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
109,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
# Clean up System books (Remove Null, Remove duplicates, format columns)
# Remove Null
Systembook = Systembook[
    (Systembook["Books"].notna()) &
    (Systembook["Books"].astype(str).str.strip().str.lower() != "nan") &
    (Systembook["Books"].astype(str).str.strip() != "")
 ]

In [58]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [59]:
#Remove Dups
Systembook = Systembook.drop_duplicates()

In [60]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [61]:


#remove the "" from date
Systembook["Book checkout"] = (
    Systembook["Book checkout"]
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.strip()
)

In [62]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,02/04/2023,25/03/2023,2 weeks,4.0
4,5.0,Dune,02/04/2023,25/03/2023,2 weeks,5.0

In [69]:
print(Systembook[["Book checkout","Book Returned"]].dtypes)

Book checkout    object
Book Returned    object
dtype: object

In [ ]:
#format checkout date
Systembook["Book checkout"] = pd.to_datetime(
    Systembook["Book checkout"],
    dayfirst=True,
    errors="coerce"
)

In [74]:
#format return date
Systembook["Book Returned"] = pd.to_datetime(
    Systembook["Book Returned"],
    dayfirst=True,
    errors="coerce"
)

In [75]:
# Function to calcualte the differnece bewteen the two date columns

def date_diff(df, start_col, end_col, new_col):
    df[new_col] = (df[end_col] - df[start_col]).dt.days
    return df

In [76]:
Systembook = date_diff(
    Systembook,
    "Book checkout",
    "Book Returned",
    "Days Borrowed"
)

In [77]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Days Borrowed
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0,-3.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0,-4.0
3,4.0,The hobbit,2023-04-02,2023-03-25,2 weeks,4.0,-8.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,-8.0

In [ ]:
# save the new file Systembook
 
Systembook.to_csv("Systembook_Clean.csv", index=False)

In [80]:
# Clean Customer file
# Remove Null

Customer = Customer[
    (Customer["Customer Name"].notna()) &
    (Customer["Customer Name"].astype(str).str.strip().str.lower() != "nan") &
    (Customer["Customer Name"].astype(str).str.strip() != "")
]

In [82]:
display(Customer.head())

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
4          5.0  William Holden
5          6.0   Jaztyn Forest

In [83]:
# save the new file customer
 
Customer.to_csv("Customer_Clean.csv", index=False)