In [1]:
#import liabry and load in the files

import pandas as pd
import os

Systembook = pd.read_csv("03_Library Systembook.csv")

Customer = pd.read_csv("03_Library SystemCustomers.csv")

display(Systembook.head())
display(Customer.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [ ]:
# Clean up System books (Remove Null, Remove duplicates, format columns)

# Remove Null
def remove_null_text_rows(df, column):
    return df[
        (df[column].notna()) &
        (df[column].astype(str).str.strip().str.lower() != "nan") &
        (df[column].astype(str).str.strip() != "")
    ]

#use
Systembook = remove_null_text_rows(Systembook, "Books")
Customer = remove_null_text_rows(Customer, "Customer Name")

In [5]:
def remove_duplicates(df):
    return df.drop_duplicates()

#use
Systembook = remove_duplicates(Systembook)
Customer = remove_duplicates(Customer)

In [10]:

#remove the "" from date
Systembook["Book checkout"] = (
    Systembook["Book checkout"]
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.strip()
)

In [11]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,02/04/2023,25/03/2023,2 weeks,4.0
4,5.0,Dune,02/04/2023,25/03/2023,2 weeks,5.0

In [12]:
print(Systembook[["Book checkout","Book Returned"]].dtypes)

Book checkout    object
Book Returned    object
dtype: object

In [13]:
def clean_date_column(df, column):
    df[column] = (
        df[column]
        .astype(str)
        .str.replace('"', '', regex=False)
        .str.strip()
    )

    df[column] = pd.to_datetime(
        df[column],
        dayfirst=True,
        errors="coerce"
    )

    return df

#use

Systembook = clean_date_column(
    Systembook,
    "Book checkout"
)

Systembook = clean_date_column(
    Systembook,
    "Book Returned"
)

In [14]:
print(Systembook[["Book checkout","Book Returned"]].dtypes)

Book checkout    datetime64[ns]
Book Returned    datetime64[ns]
dtype: object

In [15]:
# Function to calcualte the differnece bewteen the two date columns

def date_diff(df, start_col, end_col, new_col):
    df[new_col] = (df[end_col] - df[start_col]).dt.days
    return df

# use
Systembook = date_diff(
    Systembook,
    "Book checkout",
    "Book Returned",
    "Days Borrowed"
)

In [16]:
display(Systembook.head())

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Days Borrowed
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0,-3.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0,-4.0
3,4.0,The hobbit,2023-04-02,2023-03-25,2 weeks,4.0,-8.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,-8.0

In [17]:
# save the new file Systembook
 
Systembook.to_csv("Systembook_Clean.csv", index=False)

In [19]:
# save the new file customer
 
Customer.to_csv("Customer_Clean.csv", index=False)